// languages.js - 完整的多語言文字定義文件（新增整合登入和註冊頁面翻譯）
export const translations = {
  en: {
    // Welcome Page
    welcome: {
      title: 'CardReminder',
      subtitle: 'Your Smart Credit Card Manager',
      mainTitle: 'Manage Your Payments',
      description: 'Stay on top of your credit card payments with timely reminders and easy tracking.',
      startButton: 'Start Now'
    },
    
    // 🔥 新增：整合登入頁面完整英文翻譯
    integratedLogin: {
      title: 'CardReminder',
      welcomeText: 'Welcome back! Please choose your login method',
      emailMethod: 'Sign in with Email',
      phoneMethod: 'Sign in with Phone Number',
      email: 'Email',
      password: 'Password',
      phoneNumber: 'Phone Number',
      verificationCode: 'Verification Code',
      enterEmail: 'Enter your email',
      enterPassword: 'Enter your password',
      enterPhoneNumber: '9123 4567',
      enterVerificationCode: '000000',
      forgotPassword: 'Forgot Password?',
      signInButton: 'Sign In',
      signingIn: 'Signing In...',
      sendCodeButton: 'Send Verification Code',
      sendingCode: 'Sending...',
      verifyCodeButton: 'Verify Code',
      verifying: 'Verifying...',
      resendCode: 'Resend',
      resendCodeIn: 'seconds until resend',
      noAccount: "Don't have an account?",
      signUpNow: 'Sign Up Now',
      phoneHint: 'We will send a verification code to this number',
      otpHint: 'Please enter the 6-digit verification code',
      noCodeReceived: "Didn't receive the code?",
      devModeTitle: 'Development Mode',
      devModeMessage: 'Verification code "sent" to {phone}\n\n🧪 Development Mode:\n• You can use any 6-digit code\n• For example: 123456, 888888\n• This only works in development',
      codeSent: 'Verification Code Sent',
      codeSentMessage: 'SMS verification code sent to {phone}\nPlease check your messages',
      loginSuccess: 'Login Successful',
      welcomeBack: 'Welcome back, {name}!',
      getStarted: 'Get Started',
      // Error messages
      inputError: 'Input Error',
      formatError: 'Format Error',
      loginError: 'Login Error',
      sendFailed: 'Send Failed',
      verificationFailed: 'Verification Failed',
      emailRequired: 'Please enter your email address',
      passwordRequired: 'Please enter your password',
      phoneRequired: 'Please enter your phone number',
      codeRequired: 'Please enter the 6-digit verification code',
      invalidEmail: 'Please enter a valid email address',
      invalidPhone: 'Please enter a valid Hong Kong phone number',
      invalidCode: 'Verification code must be 6 digits',
      loginFailed: 'Login failed, please check your email and password',
      codeSendFailed: 'Unable to send verification code, please try again later',
      codeVerifyFailed: 'Verification code error, please check and try again',
      networkError: 'Network error, please try again later'
    },

    // 🔥 新增：整合註冊頁面完整英文翻譯
    integratedSignUp: {
      title: 'CardReminder',
      welcomeText: 'Join us! Please choose your registration method',
      emailMethod: 'Sign up with Email',
      phoneMethod: 'Sign up with Phone Number',
      username: 'Username',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      phoneNumber: 'Phone Number',
      verificationCode: 'Verification Code',
      enterUsername: 'Enter your username',
      enterEmail: 'Enter your email',
      enterPassword: 'Enter your password',
      confirmYourPassword: 'Confirm your password',
      enterPhoneNumber: '9123 4567',
      enterVerificationCode: '000000',
      createAccountButton: 'Create Account',
      creatingAccount: 'Creating Account...',
      sendCodeButton: 'Send Verification Code',
      sendingCode: 'Sending...',
      verifyCodeButton: 'Verify Code',
      verifying: 'Verifying...',
      resendCode: 'Resend',
      resendCodeIn: 'seconds until resend',
      alreadyHaveAccount: 'Already have an account?',
      signInNow: 'Sign In Now',
      termsAgreement: 'By creating an account, you agree to our',
      termsOfService: 'Terms of Service',
      and: 'and',
      privacyPolicy: 'Privacy Policy',
      phoneHint: 'We will send a verification code to this number',
      otpHint: 'Please enter the 6-digit verification code',
      noCodeReceived: "Didn't receive the code?",
      devModeTitle: 'Development Mode',
      devModeMessage: 'Verification code "sent" to {phone}\n\n🧪 Development Mode:\n• You can use any 6-digit code\n• For example: 123456, 888888\n• This only works in development',
      codeSent: 'Verification Code Sent',
      codeSentMessage: 'SMS verification code sent to {phone}\nPlease check your messages',
      signUpSuccess: '📧 Registration Successful! Please verify your email',
      emailVerificationMessage: 'Verification email sent to {email}\n\nPlease check your mailbox (including spam folder) and click the verification link to complete registration.',
      didNotReceiveEmail: "I didn't receive the email",
      checkEmail: 'OK, I\'ll check',
      resendEmailSuccess: 'Verification email resent, please check your mailbox again',
      resendEmailFailed: 'Please try again later or contact support',
      registrationSuccess: 'Registration Successful',
      welcomeMessage: '🎉 Welcome to CardReminder, {name}!',
      getStarted: 'Get Started',
      resendSuccess: 'Resend Successful',
      newCodeSent: 'New verification code sent to your phone, please check',
      // Error messages
      inputError: 'Input Error',
      formatError: 'Format Error',
      signUpError: 'Registration Error',
      sendFailed: 'Send Failed',
      verificationFailed: 'Verification Failed',
      usernameRequired: 'Please enter your username',
      usernameMinLength: 'Username must be at least 3 characters',
      emailRequired: 'Please enter your email address',
      passwordRequired: 'Please enter your password',
      phoneUsernameRequired: 'Please enter your username',
      phoneUsernameMinLength: 'Username must be at least 2 characters',
      phoneRequired: 'Please enter your phone number',
      codeRequired: 'Please enter the 6-digit verification code',
      invalidEmail: 'Please enter a valid email address',
      passwordTooShort: 'Password must be at least 6 characters',
      passwordMismatch: 'Passwords do not match',
      passwordMismatchMessage: 'The two passwords entered do not match, please re-confirm',
      invalidPhone: 'Please enter a valid Hong Kong phone number',
      invalidCode: 'Verification code must be 6 digits',
      registrationFailed: 'Registration failed, an error occurred during registration',
      codeSendFailed: 'Unable to send verification code, please try again later',
      codeVerifyFailed: 'Verification code error, please check and try again',
      networkError: 'Network error, please try again later'
    },

    // 🔥 新增：語言切換器翻譯
    languageSelector: {
      title: 'Language',
      english: 'English',
      traditionalChinese: 'Traditional Chinese',
      cancel: 'Cancel'
    },
    
    // Login Page (保留原有的，用於其他登入頁面)
    login: {
      title: 'CardReminder',
      welcome: 'Welcome back! Please sign in to your account',
      email: 'Email',
      password: 'Password',
      enterEmail: 'Enter your email',
      enterPassword: 'Enter your password',
      loginButton: 'Sign In',
      loggingIn: 'Signing In...',
      noAccount: "Don't have an account yet?",
      signUpNow: 'Sign Up Now',
      inputError: 'Input Error',
      formatError: 'Format Error',
      loginError: 'Login Error',
      pleaseEnterEmail: 'Please enter your email address',
      pleaseEnterPassword: 'Please enter your password',
      pleaseEnterValidEmail: 'Please enter a valid email address'
    },
    
    // Sign Up Page (保留原有的，用於其他註冊頁面)
    signUp: {
      title: 'Create Account',
      subtitle: 'Join CardReminder today',
      continueWithGoogle: 'Sign up with Google',
      or: 'or',
      username: 'Username',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      enterUsername: 'Enter your username',
      enterEmail: 'Enter your email',
      enterPassword: 'Enter your password',
      confirmYourPassword: 'Confirm your password',
      signUpButton: 'Sign Up',
      creatingAccount: 'Creating Account...',
      alreadyHaveAccount: 'Already have an account?',
      logIn: 'Log In',
      termsAgreement: 'By creating an account, you agree to our',
      termsOfService: 'Terms of Service',
      and: 'and',
      privacyPolicy: 'Privacy Policy',
      // Error messages
      inputError: 'Input Error',
      usernameRequired: 'Please enter your username',
      usernameMinLength: 'Username must be at least 3 characters',
      emailRequired: 'Please enter your email address',
      formatError: 'Format Error',
      invalidEmail: 'Please enter a valid email address',
      passwordRequired: 'Please enter your password',
      passwordTooShort: 'Password must be at least 6 characters',
      passwordMismatch: 'Passwords do not match',
      passwordMismatchMessage: 'The two passwords you entered do not match, please re-confirm',
      // Success messages
      signUpSuccess: 'Registration Successful!',
      verificationEmailSent: 'A verification email has been sent to {email}. Please check your mailbox and click the verification link to complete registration.',
      signUpError: 'Registration Error',
      googleSignUpError: 'Cannot connect to Google services, please try again later.'
    },

    // 🔥 新增：忘記密碼頁面完整翻譯
    forgotPassword: {
      title: 'Forgot Password?',
      subtitle: "No worries! Enter your email address and we'll send you a link to reset your password.",
      emailLabel: 'Email Address',
      emailPlaceholder: 'Enter the email you used to register',
      sendButton: 'Send Reset Email',
      sending: 'Sending...',
      emailSentTitle: 'Email Sent!',
      emailSentMessage: 'We have sent a password reset link to {email}. Please check your mailbox, including spam folder.',
      backToLogin: 'Back to Login',
      helpTitle: 'Need Help?',
      pleaseEnterEmail: 'Please enter the email address you used to register',
      pleaseEnterValidEmail: 'Please enter a valid email address',
      helpText: '• Make sure the email address you entered is the one you used to register\n• Reset email may take a few minutes to arrive\n• Please check your spam or promotional email folders\n• If you still have problems, please contact customer support',
      // Error messages
      inputError: 'Input Error',
      emailRequired: 'Please enter the email address you used to register',
      formatError: 'Format Error',
      invalidEmail: 'Please enter a valid email address',
      sendFailed: 'Send Failed',
      sendError: 'Unable to send password reset email, please try again later',
      networkError: 'An error occurred while sending the password reset email, please try again later',
      // Success messages
      resetEmailSent: '📧 Reset Email Sent!',
      resetEmailMessage: 'We have sent a password reset link to: {email}\n\nPlease check:\n✅ Inbox\n✅ Spam folder\n✅ Promotions folder\n\nClick the link in the email to reset your password.',
      checkEmail: 'OK, I\'ll check'
    },
    
// Terms of Service
terms: {
  title: 'Terms of Service',
  effectiveDate: 'Effective Date: August 2, 2025',
  lastUpdated: 'Last Updated: August 2, 2025'
},

// Privacy Policy
privacy: {
  title: 'Privacy Policy', 
  effectiveDate: 'Effective Date: August 2, 2025',
  lastUpdated: 'Last Updated: August 2, 2025'
},
    // Home Page
    home: {
      title: 'CardReminder',
      welcome: 'Welcome back',
      nextUpcomingDue: 'Next Upcoming Due Payment',
      noUpcomingPayments: 'No upcoming payments',
      paymentCalendar: 'Payment Calendar',
      paymentDue: 'Payment Due',
      paymentOverdue: 'Payment Overdue',
      paymentDueToday: 'Payment Due Today',
      paymentDueNextMonth: 'Payment Due Next Month',
      paymentDueSoon: 'Payment Due Soon',
      addCard: 'Add Card',
      myCards: 'My Cards',
      notifications: 'Notifications',
      stats: 'Stats',
      explore: 'Explore',
      daysLeft: 'days left',
      dueToday: 'Due today',
      overdue: 'days overdue',
      upcoming: 'Upcoming',
      selectMonthYear: 'Select Month & Year',
      month: 'Month',
      year: 'Year',
      confirm: 'Confirm',
      payments: 'Payments',
      futurePayment: 'Future payment',
      paid: 'Paid',
      cardsText: 'cards',
      holidays: {
        'NewYearsDay': 'New Year\'s Day',
        'LabourDay': 'Labour Day', 
        'HKSAREstablishmentDay': 'HKSAR Establishment Day',
        'NationalDay': 'National Day',
        'ChristmasDay': 'Christmas Day',
        'BoxingDay': 'Boxing Day',
        'LunarNewYearDay1': 'Lunar New Year Day 1',
        'LunarNewYearDay2': 'Lunar New Year Day 2',
        'LunarNewYearDay3': 'Lunar New Year Day 3'
      }
    },
    
    // 🔥 新增和完善：探索頁面完整翻譯
    explore: {
      title: 'Credit Card Explorer',
      subtitle: 'Discover better credit card options',
      headerTitle: 'Credit Card Explorer',
      headerSubtitle: 'Discover better credit card options',
      sectionTitle: 'Explore Better Options',
      sectionSubtitle: 'Search and compare premium credit cards',
      searchPlaceholder: 'Search card name, bank or offers...',
      yourCreditCards: 'Your Credit Cards',
      recommendedForYou: 'Recommended for You',
      myCreditCards: 'My Credit Cards',
      allCards: 'All Credit Cards',
      recommendationDescription: 'Based on your usage, these cards might suit you better',
      myCard: 'My Card',
      cashback: 'Cashback',
      userCard: 'My Card',
      noResults: 'No credit cards found matching your criteria',
      tryDifferentSearch: 'Please try different search terms',
      // 🔥 新增：收藏功能翻譯
      favorites: 'Favorites',
      myFavorites: 'My Favorites',
      addToFavorites: 'Add to Favorites',
      removeFromFavorites: 'Remove from Favorites',
      noFavoritesYet: 'No favorites yet',
      noFavoritesDescription: 'Tap the heart icon on cards to add them to your favorites',
      favoriteAdded: 'Added to favorites',
      favoriteRemoved: 'Removed from favorites',
      // 分類翻譯
      categories: {
        myCards: 'My Cards',
        all: 'All',
        basicCashback: 'Basic Cashback',
        foreignCurrency: 'Foreign Currency',
        mobilePayment: 'Mobile Payment',
        onlineShopping: 'Online Shopping',
        supermarket: 'Supermarket',
        dining: 'Dining',
        student: 'Student'
      }
    },
    
    // Profile Page
    profile: {
      title: 'Profile',
      editProfile: 'Edit Profile',
      chooseWhatToEdit: 'Choose what you want to edit',
      cancel: 'Cancel',
      changeName: 'Change Name',
      changeAvatar: 'Change Avatar',
      enterYourName: 'Enter your name',
      personalInfo: 'Personal Information',
      languageSettings: 'Language Settings',
      privacySecurity: 'Privacy & Security',
      helpSupport: 'Help & Support',
      languageChangedSuccess: 'Language changed successfully',
      languageChangedTo: 'Language changed to',
      english: 'English',
      traditionalChinese: 'Traditional Chinese',
      settings: 'Settings',
      reminderTitle: 'Get reminders now!',
      reminderSubtitle: 'Set reminders for your payments today!',
      shareApp: 'Share app',
      comingSoon: 'Coming Soon',
      logout: 'Log out',
      nameCannotBeEmpty: 'Name cannot be empty',
      profileUpdated: 'Profile updated successfully',
      avatarUpdated: 'Avatar updated successfully',
      permissionRequired: 'Permission Required',
      cameraPermissionMessage: 'Camera roll permission is required to upload avatar!',
      failedToUpdateAvatar: 'Failed to update avatar',
      logoutConfirm: 'Are you sure you want to log out?',
      logoutSuccess: 'You have been logged out successfully',
      save: 'Save',
      close: 'Close'
    },
    
    // My Cards Page
    myCards: {
      title: 'My Cards',
      totalCards: 'Total',
      paidCards: 'Paid', 
      unpaidCards: 'Unpaid',
      addCard: 'Add Card',
      paymentDue: 'Payment Due',
      paid: 'Paid',
      unpaid: 'Unpaid',
      markAsPaid: 'Mark as Paid',
      markAsUnpaid: 'Mark as Unpaid',
      notifications: 'Notifications',
      deleteCard: 'Delete Card',
      confirmDelete: 'Are you sure you want to delete',
      delete: 'Delete',
      paymentMarked: 'Payment marked successfully!',
      confirmAction: 'Confirm Action',
      markAsUnpaidConfirm: 'Mark this card as unpaid?',
      cardMarkedUnpaid: 'Card marked as unpaid',
      noCreditCards: 'No Credit Cards',
      addFirstCard: 'Add your first credit card to get started',
      due: 'Due',
      daysLeft: 'days left',
      dueToday: 'Due today',
      daysOverdue: 'days overdue',
      notificationEnabled: 'Notifications enabled',
      notificationDisabled: 'Notifications disabled',
      card: 'Card',
      cardNotFound: 'Card not found',
      confirmDeleteWithHistory: 'This will also delete related payment history.',
      cardDeleted: 'successfully deleted',
      paidThisMonth: 'Paid this month',
      paymentPending: 'Payment pending',
      swipeToDelete: 'Delete',
      swipeHint: 'Swipe left to edit or delete cards',
      edit: 'Edit',
      editCard: 'Edit Card',
      cardName: 'Card Name',
      cardNumber: 'Card Number (Last 4 digits)',
      enterCardName: 'Enter card name',
      enterCardNumber: 'Enter last 4 digits',
      cardNameRequired: 'Card name cannot be empty',
      error: 'Error',
      swipeRightForNotification: 'Swipe right for notifications',
      notificationOptions: 'Notification Options',
      turnOnNotifications: 'Turn On',
      turnOffNotifications: 'Turn Off',
      notificationSettingsFor: 'Notification Settings for',
      swipeRightHint: 'Swipe right to manage notifications',
      sortedBy: 'SORTED BY',
      dueDate: 'DUE DATE',
      remaining: 'days left',
      overdue: 'days overdue'
    },
    
    // Add Card Page
    addCard: {
      title: 'Add Card',
      lastFourDigits: 'Last 4 Digits of Card',
      cardName: 'Card Name',
      cardNamePlaceholder: 'e.g., Visa Signature, Enjoy Card',
      dueDate: 'Due Date',
      ofEachMonth: 'of each month',
      issuingBank: 'Issuing Bank',
      save: 'Save',
      success: 'Success',
      cardAdded: 'Credit card has been added successfully!',
      lastFourRequired: 'Last 4 digits are required',
      exactlyFourDigits: 'Please enter exactly 4 digits',
      cardNameRequired: 'Card name is required',
      dueDateRequired: 'Due date is required',
      validDay: 'Please enter a valid day (1-31)',
      selectBank: 'Please select an issuing bank',
      banks: {
        hsbc: 'HSBC',
        hangseng: 'Hang Seng Bank',
        aeon: 'Aeon',
        boc: 'Bank of China (Hong Kong)',
        icbc: 'ICBC (Asia)',
        scb: 'Standard Chartered',
        dbs: 'DBS Bank',
        citibank: 'Citibank',
        ccb: 'China Construction Bank (Asia)',
        bea: 'Bank of East Asia',
        other: 'Other Bank'
      }
    },
    
    // Notifications Page
    notifications: {
      title: 'Notifications',
      applyTo: 'Apply to:',
      allCards: 'All Cards',
      selectCard: 'Select Card',
      selectTime: 'Select Time',
      cardRepaymentReminder: 'Card Repayment Reminder',
      getNotifiedForDueDates: 'Get notified for credit card due dates.',
      reminderDays: 'Reminder Days',
      reminderTimes: 'Reminder Times',
      paymentOverdueAlert: 'Payment Overdue Alert',
      receiveOverdueAlerts: 'Receive alerts for payment overdue dates.',
      overdueReminderTime: 'Overdue Reminder Time',
      dailyReminderAfterOverdue: 'Daily reminder after payment overdue date',
      saveSettings: 'Save Settings',
      success: 'Success',
      notificationSettingsSaved: 'Notification settings saved',
      cancel: 'Cancel',
      notificationPermission: 'Notification Permission',
      enableNotificationPermissions: 'Please enable notification permissions in settings to receive payment reminders.',
      daysBeforeOptions: {
        7: '7 days before',
        3: '3 days before',
        2: '2 days before',
        1: '1 day before',
        0: 'Due date'
      },
      enableNotifications: 'Enable Notifications',
      scheduledNotifications: 'Scheduled Notifications',
      customSettings: 'Custom Settings',
      daysBefore: 'Days Before',
      notificationTimes: 'Notification Times',
      overdueReminders: 'Overdue Reminders',
      testNotification: 'Test Notification',
      days: 'days before',
      currentDay: 'Due date',
      testSent: 'Test notification sent!',
      settingsSaved: 'Notification settings saved!',
      morning: 'Morning',
      afternoon: 'Afternoon',
      evening: 'Evening',
      unsavedChanges: 'Unsaved Changes',
      unsavedChangesMessage: 'You have unsaved notification setting changes. Do you want to save them?',
      discardChanges: 'Discard Changes',
      saveAndExit: 'Save and Exit',
      saveChanges: 'Save Changes',
      noChangesToSave: 'No Changes to Save',
      allCardsEnabled: 'All cards notifications enabled',
      allCardsDisabled: 'All cards notifications disabled',
      getNotifiedForCard: 'Get notified for',
      dueDates: 'due dates',
      cardsEnabled: 'cards enabled'
    },
    
    // History Page
    history: {
      title: 'History',
      totalPayments: 'Total Payments',
      onTimePayments: 'On-time Payments',
      latePayments: 'Late Payments',
      onTimeRate: 'On-time Rate',
      searchPlaceholder: 'Search by card name...',
      noHistory: 'No payment history',
      noResults: 'No results found for your search',
      noHistoryDescription: 'Your payment history will appear here once you start making payments',
      paymentHistory: 'Payment History',
      onTime: 'On Time',
      late: 'Late',
      dueDate: 'Due Date',
      actualPaymentDate: 'Actual Payment Date',
      unknownCard: 'Unknown Card',
      unknownBank: 'Unknown Bank',
      notSpecified: 'Not specified',
      invalidDate: 'Invalid date',
      dateError: 'Date error'
    },
    
    // 🔥 完整修正：成就頁面翻譯（包含所有新增成就）
    achievements: {
      title: 'Achievements',
      completed: 'Completed',
      total: 'Total',
      progress: 'Progress',
      
      // 入門成就組
      gettingStarted: 'Getting Started',
      addFirstCard: 'Add your first credit card',
      firstPayment: 'First Payment',
      makeFirstPayment: 'Make your first on-time payment',
      welcomeExplorer: 'Welcome Explorer',
      visitExploreFirstTime: 'Visit the explore feature for the first time',
      
      // 信用卡管理成就組
      cardCollector: 'Card Collector',
      addThreeCards: 'Add 3 different credit cards',
      multitasker: 'Multitasker',
      manageFiveCards: 'Manage 5+ active credit cards',
      cardMaster: 'Card Master',
      manageTenCards: 'Manage 10+ active credit cards',
      bankExplorer: 'Bank Explorer',
      addCardsFiveBanks: 'Add cards from 5 different banks',
      
      // 付款管理成就組
      perfectWeek: 'Perfect Week',
      noMissedPayments7Days: 'No missed payments for 7 days',
      monthlyChampion: 'Monthly Champion',
      payAllCardsOnTime: 'Pay all cards on time for a month',
      streakMaster: 'Streak Master',
      maintain90DayStreak: 'Maintain 90-day payment streak',
      earlyBird: 'Early Bird',
      pay10BillsEarly: 'Pay 10 bills early (before due date)',
      neverLate: 'Never Late',
      perfectRecord6Months: 'Perfect payment record for 6 months',
      perfectionist: 'Perfectionist',
      hundredPercentOnTime: '100% on-time payment rate',
      centuryClub: 'Century Club',
      make100Payments: 'Make 100 successful payments',
      
      // 探索功能成就組
      curiousExplorer: 'Curious Explorer',
      visitExplore10Times: 'Visit the explore feature 10 times',
      searchMaster: 'Search Master',
      performSearches25Times: 'Perform card searches 25 times',
      filterExpert: 'Filter Expert',
      useFilters15Times: 'Use category filters 15 times',
      comparisonAnalyst: 'Comparison Analyst',
      compareCards5Times: 'Compare different cards 5 times',
      
      // 收藏系統成就組
      firstFavorite: 'First Favorite',
      addFirstFavorite: 'Add your first favorite card',
      favoriteCollector: 'Favorite Collector',
      add10Favorites: 'Add 10 cards to favorites',
      wishlistMaster: 'Wishlist Master',
      maintain20Favorites: 'Maintain 20+ cards in favorites',
      
      // 個人化成就組
      profilePerfectionist: 'Profile Perfectionist',
      updateProfile5Times: 'Update your profile 5 times',
      multilingual: 'Multilingual',
      switchLanguages3Times: 'Switch between languages 3 times',
      notificationMaster: 'Notification Master',
      setupNotificationsAllCards: 'Set up notifications for all cards',
      techSavvy: 'Tech Savvy',
      customizeNotifications: 'Customize notification settings',
      
      // 長期使用成就組
      reliableUser: 'Reliable User',
      useApp30Days: 'Use the app for 30 consecutive days',
      persistenceKing: 'Persistence King',
      useApp100Days: 'Use the app for 100 consecutive days',
      veteranUser: 'Veteran User',
      useAppFullYear: 'Use the app for a full year',
      dailyChampion: 'Daily Champion',
      loginDaily30Days: 'Login daily for 30 consecutive days',
      
      // 進階功能成就組
      calendarMaster: 'Calendar Master',
      useCalendar20Times: 'Use payment calendar feature 20 times',
      powerUser: 'Power User',
      useAllFeatures: 'Use all major app features at least once',
      organizationMaster: 'Organization Master',
      setupNotificationsAllCards: 'Set up notifications for all cards',
      
      // 特殊成就組
      earlyAdopter: 'Early Adopter',
      joinedWithinFirstMonth: 'Joined the app within the first month of launch',
      feedbackHero: 'Feedback Hero',
      provideFeedback5Times: 'Provide feedback or suggestions 5 times',
      sharingEnthusiast: 'Sharing Enthusiast',
      shareApp3Times: 'Share the app with friends 3 times'
    },
    
    // Common
    common: {
      close: 'Close',
      save: 'Save',
      cancel: 'Cancel',
      confirm: 'Confirm',
      success: 'Success',
      error: 'Error',
      loading: 'Loading...',
      ok: 'OK',
      yes: 'Yes',
      no: 'No',
      delete: 'Delete',
      edit: 'Edit',
      back: 'Back',
      next: 'Next',
      done: 'Done'
    }
  },
  
  'zh-TW': {
    // Welcome Page
    welcome: {
      title: '信用卡管家',
      subtitle: '您的智能信用卡管理器',
      mainTitle: '管理您的付款',
      description: '透過及時提醒和輕鬆追蹤，掌握您的信用卡付款。',
      startButton: '立即開始'
    },
    
    // 🔥 新增：整合登入頁面完整繁體中文翻譯
    integratedLogin: {
      title: 'CardReminder',
      welcomeText: '歡迎回來！請選擇登入方式',
      emailMethod: '使用電子郵件登入',
      phoneMethod: '使用手機號碼登入',
      email: '電子郵件',
      password: '密碼',
      phoneNumber: '手機號碼',
      verificationCode: '驗證碼',
      enterEmail: '輸入您的電子郵件',
      enterPassword: '輸入您的密碼',
      enterPhoneNumber: '9123 4567',
      enterVerificationCode: '000000',
      forgotPassword: '忘記密碼？',
      signInButton: '登入',
      signingIn: '登入中...',
      sendCodeButton: '發送驗證碼',
      sendingCode: '發送中...',
      verifyCodeButton: '確認驗證碼',
      verifying: '驗證中...',
      resendCode: '重新發送',
      resendCodeIn: '秒後可重新發送',
      noAccount: '還沒有帳戶？',
      signUpNow: '立即註冊',
      phoneHint: '我們將發送驗證碼到這個號碼',
      otpHint: '請輸入收到的6位數驗證碼',
      noCodeReceived: '沒有收到驗證碼？',
      devModeTitle: '開發模式提示',
      devModeMessage: '模擬驗證碼已"發送"至 {phone}\n\n🧪 開發模式說明：\n• 您可以使用任何6位數字作為驗證碼\n• 例如：123456、888888等\n• 這僅在開發環境中有效',
      codeSent: '驗證碼已發送',
      codeSentMessage: 'SMS驗證碼已發送至 {phone}\n請檢查您的手機短信',
      loginSuccess: '登入成功',
      welcomeBack: '歡迎回來，{name}！',
      getStarted: '開始使用',
      // Error messages
      inputError: '輸入錯誤',
      formatError: '格式錯誤',
      loginError: '登入錯誤',
      sendFailed: '發送失敗',
      verificationFailed: '驗證失敗',
      emailRequired: '請輸入您的電子郵件地址',
      passwordRequired: '請輸入您的密碼',
      phoneRequired: '請輸入您的手機號碼',
      codeRequired: '請輸入6位數驗證碼',
      invalidEmail: '請輸入有效的電子郵件地址',
      invalidPhone: '請輸入有效的香港手機號碼',
      invalidCode: '驗證碼必須是6位數字',
      loginFailed: '登入失敗，請檢查您的電子郵件和密碼',
      codeSendFailed: '無法發送驗證碼，請稍後再試',
      codeVerifyFailed: '驗證碼錯誤，請檢查後重新輸入',
      networkError: '網絡錯誤，請稍後再試'
    },

    // 🔥 新增：整合註冊頁面完整繁體中文翻譯
    integratedSignUp: {
      title: 'CardReminder',
      welcomeText: '加入我們！請選擇註冊方式',
      emailMethod: '使用電子郵件註冊',
      phoneMethod: '使用手機號碼註冊',
      username: '用戶名',
      email: '電子郵件',
      password: '密碼',
      confirmPassword: '確認密碼',
      phoneNumber: '手機號碼',
      verificationCode: '驗證碼',
      enterUsername: '輸入您的用戶名',
      enterEmail: '輸入您的電子郵件',
      enterPassword: '輸入您的密碼',
      confirmYourPassword: '再次輸入您的密碼',
      enterPhoneNumber: '9123 4567',
      enterVerificationCode: '000000',
      createAccountButton: '創建帳戶',
      creatingAccount: '註冊中...',
      sendCodeButton: '發送驗證碼',
      sendingCode: '發送中...',
      verifyCodeButton: '確認驗證碼',
      verifying: '驗證中...',
      resendCode: '重新發送',
      resendCodeIn: '秒後可重新發送',
      alreadyHaveAccount: '已經有帳戶了？',
      signInNow: '立即登入',
      termsAgreement: '創建帳戶即表示您同意我們的',
      termsOfService: '服務條款',
      and: '和',
      privacyPolicy: '隱私政策',
      phoneHint: '我們將發送驗證碼到這個號碼',
      otpHint: '請輸入收到的6位數驗證碼',
      noCodeReceived: '沒有收到驗證碼？',
      devModeTitle: '開發模式提示',
      devModeMessage: '模擬驗證碼已"發送"至 {phone}\n\n🧪 開發模式說明：\n• 您可以使用任何6位數字作為驗證碼\n• 例如：123456、888888等\n• 這僅在開發環境中有效',
      codeSent: '驗證碼已發送',
      codeSentMessage: 'SMS驗證碼已發送至 {phone}\n請檢查您的手機短信',
      signUpSuccess: '📧 註冊成功！請驗證您的郵件',
      emailVerificationMessage: '驗證郵件已發送至 {email}\n\n請檢查您的郵箱（包括垃圾郵件文件夾）並點擊驗證連結完成註冊。',
      didNotReceiveEmail: '我沒收到郵件',
      checkEmail: '好的，我去檢查',
      resendEmailSuccess: '驗證郵件已重新發送，請再次檢查郵箱',
      resendEmailFailed: '請稍後再試或聯繫支援',
      registrationSuccess: '註冊成功',
      welcomeMessage: '🎉 歡迎加入CardReminder，{name}！',
      getStarted: '開始使用',
      resendSuccess: '重新發送成功',
      newCodeSent: '新的驗證碼已發送到您的手機，請查收',
      // Error messages
      inputError: '輸入錯誤',
      formatError: '格式錯誤',
      signUpError: '註冊錯誤',
      sendFailed: '發送失敗',
      verificationFailed: '驗證失敗',
      usernameRequired: '請輸入您的用戶名稱',
      usernameMinLength: '用戶名稱至少需要 3 個字符',
      emailRequired: '請輸入您的電子郵件地址',
      passwordRequired: '請輸入您的密碼',
      phoneUsernameRequired: '請輸入您的用戶名稱',
      phoneUsernameMinLength: '用戶名稱至少需要 2 個字符',
      phoneRequired: '請輸入您的手機號碼',
      codeRequired: '請輸入6位數驗證碼',
      invalidEmail: '請輸入有效的電子郵件地址',
      passwordTooShort: '密碼至少需要 6 個字符',
      passwordMismatch: '密碼不匹配',
      passwordMismatchMessage: '兩次輸入的密碼不一致，請重新確認',
      invalidPhone: '請輸入有效的香港手機號碼',
      invalidCode: '驗證碼必須是6位數字',
      registrationFailed: '註冊失敗，註冊過程中發生錯誤',
      codeSendFailed: '無法發送驗證碼，請稍後再試',
      codeVerifyFailed: '驗證碼錯誤，請檢查後重新輸入',
      networkError: '網絡錯誤，請稍後再試'
    },

    // 🔥 新增：語言切換器翻譯
    languageSelector: {
      title: '語言',
      english: 'English',
      traditionalChinese: '繁體中文',
      cancel: '取消'
    },
    
    // Login Page
    login: {
      title: 'CardReminder',
      continueWithGoogle: '使用 Google 繼續',
      or: '或',
      email: '電子郵件',
      password: '密碼',
      enterEmail: '輸入您的電子郵件',
      enterPassword: '輸入您的密碼',
      noAccount: '還沒有帳戶嗎？',
      signUpNow: '立即註冊',
      loginError: '登入錯誤',
      cannotConnectGoogle: '無法連接到 Google 服務，請稍後再試。',
      inputError: '輸入錯誤',
      pleaseEnterEmail: '請輸入您的電子郵件地址',
      pleaseEnterPassword: '請輸入您的密碼',
      formatError: '格式錯誤',
      pleaseEnterValidEmail: '請輸入有效的電子郵件地址',
      featureInDevelopment: '功能開發中',
      signUpInDevelopment: '註冊功能正在開發中，請稍後再試。'
    },
    
    // Sign Up Page
    signUp: {
      title: '建立帳戶',
      subtitle: '立即加入 CardReminder',
      continueWithGoogle: '使用 Google 註冊',
      or: '或',
      username: '用戶名稱',
      email: '電子郵件',
      password: '密碼',
      confirmPassword: '確認密碼',
      enterUsername: '輸入您的用戶名稱',
      enterEmail: '輸入您的電子郵件',
      enterPassword: '輸入您的密碼',
      confirmYourPassword: '確認您的密碼',
      signUpButton: '註冊',
      creatingAccount: '正在建立帳戶...',
      alreadyHaveAccount: '已經有帳戶了嗎？',
      logIn: '登入',
      termsAgreement: '建立帳戶即表示您同意我們的',
      termsOfService: '服務條款',
      and: '和',
      privacyPolicy: '隱私政策',
      // Error messages
      inputError: '輸入錯誤',
      usernameRequired: '請輸入您的用戶名稱',
      usernameMinLength: '用戶名稱至少需要 3 個字符',
      emailRequired: '請輸入您的電子郵件地址',
      formatError: '格式錯誤',
      invalidEmail: '請輸入有效的電子郵件地址',
      passwordRequired: '請輸入您的密碼',
      passwordTooShort: '密碼至少需要 6 個字符',
      passwordMismatch: '密碼不匹配',
      passwordMismatchMessage: '兩次輸入的密碼不一致，請重新確認',
      // Success messages
      signUpSuccess: '註冊成功！',
      verificationEmailSent: '驗證郵件已發送至 {email}，請檢查您的郵箱並點擊驗證連結完成註冊。',
      signUpError: '註冊錯誤',
      googleSignUpError: '無法連接到 Google 服務，請稍後再試。'
    },

    // 🔥 新增：忘記密碼頁面完整翻譯
    forgotPassword: {
      title: '忘記密碼？',
      subtitle: '沒關係！輸入您的電子郵件地址，我們會發送重置密碼的連結給您。',
      emailLabel: '電子郵件地址',
      emailPlaceholder: '輸入您註冊時使用的電子郵件',
      sendButton: '發送重置郵件',
      sending: '發送中...',
      emailSentTitle: '郵件已發送！',
      emailSentMessage: '我們已經向 {email} 發送了密碼重置連結。請檢查您的郵箱，包括垃圾郵件文件夾。',
      backToLogin: '返回登入頁面',
      helpTitle: '需要幫助？',
      pleaseEnterEmail: '請輸入您註冊時使用的電子郵件地址',
      pleaseEnterValidEmail: '請輸入有效的電子郵件地址',
      helpText: '• 請確保輸入的電子郵件地址是您註冊時使用的地址\n• 重置郵件可能需要幾分鐘才能送達\n• 請檢查垃圾郵件或促銷郵件文件夾\n• 如果仍有問題，請聯繫客服支援',
      // Error messages
      inputError: '輸入錯誤',
      emailRequired: '請輸入您註冊時使用的電子郵件地址',
      formatError: '格式錯誤',
      invalidEmail: '請輸入有效的電子郵件地址',
      sendFailed: '發送失敗',
      sendError: '無法發送密碼重置郵件，請稍後再試',
      networkError: '發送密碼重置郵件時發生錯誤，請稍後再試',
      // Success messages
      resetEmailSent: '📧 重置郵件已發送！',
      resetEmailMessage: '我們已將密碼重置連結發送到：{email}\n\n請檢查：\n✅ 收件箱\n✅ 垃圾郵件文件夾\n✅ 促銷文件夾\n\n點擊郵件中的連結即可重設密碼。',
      checkEmail: '好的，我去檢查'
    },
    
// 服務條款
terms: {
  title: '服務條款',
  effectiveDate: '生效日期：2025年8月2日',
  lastUpdated: '最後更新：2025年8月2日'
},

// 隱私政策  
privacy: {
  title: '隱私政策',
  effectiveDate: '生效日期：2025年8月2日',
  lastUpdated: '最後更新：2025年8月2日'
},

    // Home Page
    home: {
      title: '信用卡管家',
      welcome: '歡迎回來',
      nextUpcomingDue: '即將到期付款',
      noUpcomingPayments: '無即將到期付款',
      paymentCalendar: '付款日曆',
      paymentDue: '付款到期',
      paymentOverdue: '付款逾期',
      paymentDueToday: '今日付款到期',
      paymentDueNextMonth: '下月付款到期',
      paymentDueSoon: '付款即將到期',
      addCard: '新增卡片',
      myCards: '我的卡片',
      notifications: '通知',
      stats: '統計',
      explore: '探索',
      daysLeft: '天剩餘',
      dueToday: '今日到期',
      overdue: '天逾期',
      upcoming: '即將到期',
      selectMonthYear: '選擇月份和年份',
      month: '月份',
      year: '年份',
      confirm: '確認',
      payments: '付款',
      futurePayment: '未來付款',
      paid: '已付款',
      cardsText: '張卡片',
      holidays: {
        'NewYearsDay': '元旦',
        'LabourDay': '勞動節',
        'HKSAREstablishmentDay': '香港特別行政區成立紀念日', 
        'NationalDay': '國慶日',
        'ChristmasDay': '聖誕節',
        'BoxingDay': '節禮日',
        'LunarNewYearDay1': '農曆新年初一',
        'LunarNewYearDay2': '農曆新年初二',
        'LunarNewYearDay3': '農曆新年初三'
      }
    },
    
    // 🔥 新增和完善：探索頁面完整翻譯
    explore: {
      title: '信用卡特色探索',
      subtitle: '了解您的卡片優勢，發現更好選擇',
      headerTitle: '信用卡特色探索',
      headerSubtitle: '了解您的卡片優勢，發現更好選擇',
      sectionTitle: '探索更好的選擇',
      sectionSubtitle: '搜索和比較其他優質信用卡',
      searchPlaceholder: '搜索信用卡名稱、銀行或優惠...',
      yourCreditCards: '您的信用卡',
      recommendedForYou: '為您推薦',
      myCreditCards: '我的信用卡',
      allCards: '所有信用卡',
      recommendationDescription: '基於您的使用習慣，這些卡片可能更適合您',
      myCard: '我的卡片',
      cashback: '回贈',
      userCard: '我的卡片',
      noResults: '沒有找到符合條件的信用卡',
      tryDifferentSearch: '請嘗試不同的搜尋條件',
      // 🔥 新增：收藏功能翻譯
      favorites: '收藏',
      myFavorites: '我的收藏',
      addToFavorites: '加入收藏',
      removeFromFavorites: '移除收藏',
      noFavoritesYet: '尚未收藏任何卡片',
      noFavoritesDescription: '點擊卡片上的愛心圖示來收藏您喜歡的信用卡',
      favoriteAdded: '已加入收藏',
      favoriteRemoved: '已移除收藏',
      // 分類翻譯
      categories: {
        myCards: '我的信用卡',
        all: '全部',
        basicCashback: '基本回贈',
        foreignCurrency: '外幣',
        mobilePayment: '手機支付',
        onlineShopping: '網購',
        supermarket: '超市',
        dining: '餐飲',
        student: '學生'
      }
    },
    
    // Profile Page  
    profile: {
      title: '個人資料',
      editProfile: '編輯個人資料',
      chooseWhatToEdit: '選擇要編輯的項目',
      cancel: '取消',
      changeName: '更改姓名',
      changeAvatar: '更改頭像',
      enterYourName: '輸入您的姓名',
      personalInfo: '個人資訊',
      languageSettings: '語言設定',
      privacySecurity: '隱私與安全',
      helpSupport: '幫助與支援',
      languageChangedSuccess: '語言已成功更改',
      languageChangedTo: '語言已更改為',
      english: 'English',
      traditionalChinese: '繁體中文',
      settings: '設定',
      reminderTitle: '立即獲取提醒！',
      reminderSubtitle: '今天就為您的付款設定提醒！',
      shareApp: '分享應用程式',
      comingSoon: '即將推出',
      logout: '登出',
      nameCannotBeEmpty: '姓名不能為空',
      profileUpdated: '個人資料更新成功',
      avatarUpdated: '頭像更新成功',
      permissionRequired: '需要權限',
      cameraPermissionMessage: '需要相機膠卷權限才能上傳頭像！',
      failedToUpdateAvatar: '更新頭像失敗',
      logoutConfirm: '您確定要登出嗎？',
      logoutSuccess: '您已成功登出',
      save: '儲存',
      close: '關閉'
    },
    
    // My Cards Page
    myCards: {
      title: '我的卡片',
      totalCards: '總計',
      paidCards: '已付款',
      unpaidCards: '未付款',
      addCard: '新增卡片',
      paymentDue: '付款到期',
      paid: '已付款',
      unpaid: '未付款',
      markAsPaid: '標記為已付款',
      markAsUnpaid: '標記為未付款',
      notifications: '通知',
      deleteCard: '刪除卡片',
      confirmDelete: '您確定要刪除',
      delete: '刪除',
      paymentMarked: '付款標記成功！',
      confirmAction: '確認操作',
      markAsUnpaidConfirm: '將此卡片標記為未付款？',
      cardMarkedUnpaid: '卡片已標記為未付款',
      noCreditCards: '無信用卡',
      addFirstCard: '新增您的第一張信用卡以開始使用',
      due: '到期',
      daysLeft: '天剩餘',
      dueToday: '今日到期',
      daysOverdue: '天逾期',
      notificationEnabled: '已開啟通知',
      notificationDisabled: '已關閉通知',
      card: '信用卡',
      cardNotFound: '找不到指定的信用卡',
      confirmDeleteWithHistory: '此操作將同時刪除相關的付款歷史記錄。',
      cardDeleted: '已成功刪除',
      paidThisMonth: '本月已還款',
      paymentPending: '等待還款',
      swipeToDelete: '刪除',
      swipeHint: '向左滑動可編輯或刪除卡片',
      edit: '編輯',
      editCard: '編輯信用卡',
      cardName: '卡片名稱',
      cardNumber: '卡片號碼（後四位）',
      enterCardName: '請輸入卡片名稱',
      enterCardNumber: '請輸入卡片號碼後四位',
      cardNameRequired: '卡片名稱不能為空',
      error: '錯誤',
      swipeRightForNotification: '向右滑動管理通知',
      notificationOptions: '通知選項',
      turnOnNotifications: '開啟',
      turnOffNotifications: '關閉',
      notificationSettingsFor: '通知設定',
      swipeRightHint: '向右滑動可管理通知設定',
      sortedBy: '排序方法',
      dueDate: '到期日',
      remaining: '剩餘',
      overdue: '逾期'
    },
    
    // Add Card Page
    addCard: {
      title: '新增卡片',
      lastFourDigits: '信用卡最後4位數字',
      cardName: '卡片名稱',
      cardNamePlaceholder: '例如：Visa Signature、Enjoy Card',
      dueDate: '到期日',
      ofEachMonth: '每月',
      issuingBank: '發卡銀行',
      save: '儲存',
      success: '成功',
      cardAdded: '信用卡已成功新增！',
      lastFourRequired: '需要輸入最後4位數字',
      exactlyFourDigits: '請輸入完整的4位數字',
      cardNameRequired: '需要輸入卡片名稱',
      dueDateRequired: '需要輸入到期日',
      validDay: '請輸入有效的日期 (1-31)',
      selectBank: '請選擇發卡銀行',
      banks: {
        hsbc: '匯豐銀行',
        hangseng: '恒生銀行',
        aeon: 'Aeon',
        boc: '中國銀行',
        icbc: '中國工商銀行 (亞洲)',
        scb: '渣打銀行',
        dbs: '星展銀行',
        citibank: '花旗銀行',
        ccb: '中國建設銀行',
        bea: '東亞銀行',
        other: '其他銀行'
      }
    },
    
    // Notifications Page
    notifications: {
      title: '通知',
      applyTo: '套用至：',
      allCards: '所有卡片',
      selectCard: '選擇卡片',
      selectTime: '選擇時間',
      cardRepaymentReminder: '信用卡還款提醒',
      getNotifiedForDueDates: '接收信用卡到期日通知。',
      reminderDays: '提醒天數',
      reminderTimes: '提醒時間',
      paymentOverdueAlert: '付款逾期警示',
      receiveOverdueAlerts: '接收付款逾期日期警示。',
      overdueReminderTime: '逾期提醒時間',
      dailyReminderAfterOverdue: '付款逾期日後的每日提醒',
      saveSettings: '儲存設定',
      success: '成功',
      notificationSettingsSaved: '通知設定已儲存',
      cancel: '取消',
      notificationPermission: '通知權限',
      enableNotificationPermissions: '請在設定中啟用通知權限以接收付款提醒。',
      daysBeforeOptions: {
        7: '7 天前',
        3: '3 天前',
        2: '2 天前',
        1: '1 天前',
        0: '到期日'
      },
      enableNotifications: '啟用通知',
      scheduledNotifications: '排程通知',
      customSettings: '自訂設定',
      daysBefore: '提前天數',
      notificationTimes: '通知時間',
      overdueReminders: '逾期提醒',
      testNotification: '測試通知',
      days: '天前',
      currentDay: '到期日',
      testSent: '測試通知已發送！',
      settingsSaved: '通知設定已儲存！',
      morning: '早上',
      afternoon: '下午',
      evening: '晚上',
      unsavedChanges: '未保存的變更',
      unsavedChangesMessage: '您有未保存的通知設定變更，是否要保存？',
      discardChanges: '捨棄變更',
      saveAndExit: '保存並退出',
      saveChanges: '保存變更',
      noChangesToSave: '無變更需保存',
      allCardsEnabled: '已開啟所有卡片的通知',
      allCardsDisabled: '已關閉所有卡片的通知',
      getNotifiedForCard: '接收',
      dueDates: '到期日通知',
      cardsEnabled: '張卡片已啟用'
    },
    
    // History Page
    history: {
      title: '歷史記錄',
      totalPayments: '總付款次數',
      onTimePayments: '準時付款',
      latePayments: '遲到付款',
      onTimeRate: '準時率',
      searchPlaceholder: '依卡片名稱搜尋...',
      noHistory: '無付款歷史',
      noResults: '未找到符合搜尋條件的結果',
      noHistoryDescription: '當您開始付款後，付款歷史將會在此顯示',
      paymentHistory: '付款歷史',
      onTime: '準時',
      late: '遲到',
      dueDate: '到期日期',
      actualPaymentDate: '實際付款日期',
      unknownCard: '未知卡片',
      unknownBank: '未知銀行',
      notSpecified: '未指定',
      invalidDate: '無效日期',
      dateError: '日期錯誤'
    },
    
    // 🔥 完整修正：成就頁面翻譯（包含所有新增成就）
    achievements: {
      title: '成就',
      completed: '已完成',
      total: '總計',
      progress: '進度',
      
      // 入門成就組
      gettingStarted: '入門',
      addFirstCard: '新增您的第一張信用卡',
      firstPayment: '首次付款',
      makeFirstPayment: '完成第一次按時付款',
      welcomeExplorer: '歡迎探索者',
      visitExploreFirstTime: '首次使用探索功能',
      
      // 信用卡管理成就組
      cardCollector: '卡片收集者',
      addThreeCards: '新增 3 張不同的信用卡',
      multitasker: '多工處理者',
      manageFiveCards: '管理 5 張以上活躍信用卡',
      cardMaster: '卡片大師',
      manageTenCards: '管理 10 張以上活躍信用卡',
      bankExplorer: '銀行探索者',
      addCardsFiveBanks: '新增來自 5 家不同銀行的卡片',
      
      // 付款管理成就組
      perfectWeek: '完美一週',
      noMissedPayments7Days: '7 天內無錯過付款',
      monthlyChampion: '月度冠軍',
      payAllCardsOnTime: '一個月內所有卡片按時付款',
      streakMaster: '連勝大師',
      maintain90DayStreak: '保持 90 天付款連勝',
      earlyBird: '早起鳥',
      pay10BillsEarly: '提前支付 10 次帳單（在到期日前）',
      neverLate: '從不遲到',
      perfectRecord6Months: '6 個月完美付款記錄',
      perfectionist: '完美主義者',
      hundredPercentOnTime: '100% 按時付款率',
      centuryClub: '百次俱樂部',
      make100Payments: '完成 100 次成功付款',
      
      // 探索功能成就組
      curiousExplorer: '好奇探索者',
      visitExplore10Times: '使用探索功能 10 次',
      searchMaster: '搜索大師',
      performSearches25Times: '執行卡片搜索 25 次',
      filterExpert: '篩選專家',
      useFilters15Times: '使用分類篩選器 15 次',
      comparisonAnalyst: '比較分析師',
      compareCards5Times: '比較不同卡片 5 次',
      
      // 收藏系統成就組
      firstFavorite: '首個收藏',
      addFirstFavorite: '添加您的第一張收藏卡片',
      favoriteCollector: '收藏收集者',
      add10Favorites: '收藏 10 張卡片',
      wishlistMaster: '願望清單大師',
      maintain20Favorites: '維持 20 張以上收藏卡片',
      
      // 個人化成就組
      profilePerfectionist: '個人資料完美主義者',
      updateProfile5Times: '更新個人資料 5 次',
      multilingual: '多語言使用者',
      switchLanguages3Times: '在語言間切換 3 次',
      notificationMaster: '通知大師',
      setupNotificationsAllCards: '為所有卡片設定通知',
      techSavvy: '科技達人',
      customizeNotifications: '自訂通知設定',
      
      // 長期使用成就組
      reliableUser: '可靠用戶',
      useApp30Days: '連續使用應用程式 30 天',
      persistenceKing: '堅持之王',
      useApp100Days: '連續使用應用程式 100 天',
      veteranUser: '資深用戶',
      useAppFullYear: '使用應用程式滿一年',
      dailyChampion: '每日冠軍',
      loginDaily30Days: '連續 30 天每日登入',
      
      // 進階功能成就組
      calendarMaster: '日曆大師',
      useCalendar20Times: '使用付款日曆功能 20 次',
      powerUser: '高級用戶',
      useAllFeatures: '至少使用所有主要應用功能一次',
      organizationMaster: '組織大師',
      setupNotificationsAllCards: '為所有卡片設定通知',
      
      // 特殊成就組
      earlyAdopter: '早期採用者',
      joinedWithinFirstMonth: '在應用程式推出第一個月內加入',
      feedbackHero: '回饋英雄',
      provideFeedback5Times: '提供意見或建議 5 次',
      sharingEnthusiast: '分享愛好者',
      shareApp3Times: '與朋友分享應用程式 3 次'
    },
    
    // Common
    common: {
      close: '關閉',
      save: '儲存',
      cancel: '取消',
      confirm: '確認',
      success: '成功',
      error: '錯誤',
      loading: '載入中...',
      ok: '確定',
      yes: '是',
      no: '否',
      delete: '刪除',
      edit: '編輯',
      back: '返回',
      next: '下一步',
      done: '完成'
    }
  }
};